version: 0.0.{build}-pre
image: Visual Studio 2022 
install:
  - ps: dotnet --version
  - ps: dotnet tool restore
  - ps: dotnet restore
build_script:
  - ps: dotnet build Polly.Tick.sln
  - ps: dotnet pack --configuration Release
test_script:
  - ps: dotnet tool run dotnet-format -- --check
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test $proj.FullName }
artifacts:
  - path: '**/*.nupkg'
    name: NuGet Packages
