version: 0.0.{build}-pre
image: Visual Studio 2017
install:
  - ps: dotnet --version
  - ps: dotnet restore
build_script:
  - ps: dotnet build Polly.Tick.sln
test_script:
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test $proj.FullName }
